services:
  sample:
    build:
      context: ./src/mcp_servers/sample
      dockerfile: Dockerfile
      args:
        HOST: 0.0.0.0
        PORT: 1111
    container_name: sample-server
    ports:
      - "1111:1111"
    restart: unless-stopped

  gemini:
    build:
      context: ./src/mcp_servers/gemini
      dockerfile: Dockerfile
      args:
        HOST: 0.0.0.0
        PORT: 1113
    volumes:
      - ./key.env:/app/key.env
    container_name: gemini-server
    ports:
      - "1113:1113"
    restart: unless-stopped

  medgemma:
    build:
      context: ./src/mcp_servers/medgemma
      dockerfile: Dockerfile
      args:
        HOST: 0.0.0.0
        PORT: 1114
    container_name: medgemma-server
    ports:
      - "1114:1114"
    restart: unless-stopped
    volumes:
      - slum-volume:/mnt/slum
      - ./key.env:/app/key.env
    gpus:
      - count: all
      - devices: all

  medgemma-bnb:
    build:
      context: ./src/mcp_servers/medgemma-bnb
      dockerfile: Dockerfile
      args:
        HOST: 0.0.0.0
        PORT: 1115
    container_name: medgemma-bnb-server
    ports:
      - "1115:1115"
    restart: unless-stopped
    volumes:
      - slum-volume:/mnt/slum
      - ./key.env:/app/key.env
    gpus:
      - count: all
      - devices: all
      
  medgemma-bnb-2:
    build:
      context: ./src/mcp_servers/medgemma-bnb
      dockerfile: Dockerfile
      args:
        HOST: 0.0.0.0
        PORT: 1116
    container_name: medgemma-bnb-2-server
    ports:
      - "1116:1116"
    restart: unless-stopped
    volumes:
      - slum-volume:/mnt/slum
      - ./key.env:/app/key.env
    gpus:
      - count: all
      - devices: all

# volumeは外部ボリュームを使用するため、事前に作成しておく必要があります。
volumes:
  slum-volume:
    external: true

