pipeline:
  # MCP API 設定
  mcp_urls: ["http://localhost:10003/mcp/", "http://localhost:10005/mcp/"]

container:
  medgemma:
    mcp_name: "medgemma-4b-it" # MCP名
    model_id: "/mnt/slum/models/medgemma-4b-it" # google/medgemma-4b-it
    quant_mode: 4bit # 量子化モード (4bit, 8bit, or None)
    max_tokens: 512 # 最大トークン数
    temperature: 0.2 # 温度パラメータ

  mediphi:
    mcp_name: "Mediphi-it" # MCP名
    model_id: "/mnt/slum/models/MediPhi-it" # microsoft/MediPhi-it
    quant_mode: 4bit # 量子化モード (4bit, 8bit, or None)
    max_tokens: 512 # 最大トークン数
    temperature: 0.2 # 温度パラメータ

  blip:
    model_id: "/mnt/slum/models/blip-image-captioning-large" # Salesforce/blip-image-captioning-large
    quant_mode: 4bit # 量子化モード (4bit, 8bit, or None)
    max_tokens: 50 # 最大トークン数
    temperature: 0.2 # 温度パラメータ

  lingshu:
    mcp_name: "Lingshu-7b" # MCP名
    model_id: "/mnt/slum/models/Lingshu-7b" # lingshu-medical-mllm/Lingshu-7B
    quant_mode: 4bit # 量子化モード (4bit, 8bit, or None)
    max_tokens: 512 # 最大トークン数
    temperature: 0.2 # 温度パラメータ